language: go

go:
    - 1.3
    - 1.4
    - tip

install:
    - go get github.com/lib/pq
    - go get gopkg.in/gorp.v1
    - go get github.com/stretchr/testify/assert
    - go get golang.org/x/crypto/bcrypt
